[project]
name = 'Backend'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.clarity-bitcoin-mini]
path = 'contracts/clarity-bitcoin-mini.clar'
clarity_version = 2
epoch = 2.5

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.sbtc]
path = 'contracts/sbtc.clar'
clarity_version = 2
epoch = 2.5

[contracts.stream]
path = 'contracts/stream.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
